Add support for php 8 & update dependencies to their latest versions
Commercie/currency pull request #6
Opened 2021-04-28 13:13 UTC by TomKeyte

PHP 8 has been released.

This PR adds support for it, as well as updates the dependencies to their latest versions

2021-05-06 21:17 UTC, bartfeenstra commented
This looks good! To confirm this all works on PHP 8, can you update `.travis.yml`?

2021-05-07 08:19 UTC, TomKeyte commented
> This looks good! To confirm this all works on PHP 8, can you update `.travis.yml`?

Will do.

Perhaps I should remove support for PHP 5, and <=7.3 since they are all EOL?

2021-05-07 08:28 UTC, bartfeenstra commented
Removing support for EOL versions would be a BC break and require a new major version release. First of all that would therefore have to be done in a separate PR, but as I am no longer actively maintaining this package that seems like an unnecessary disruption at this point.

2021-07-09 08:45 UTC, TomKeyte commented
Apologies, forgot to get around to this

Haven't used travis before - hoping just adding php 8 will be enough :)

2021-07-09 10:02 UTC, bartfeenstra requested changes

2021-07-09 10:02 UTC, bartfeenstra commented on .phpunit.result.cache
> +C:37:"PHPUnit\Runner\DefaultTestResultCache":2085:{a:2:{s:7:"defects";a:0:{}s:5:"times";a:25:{s:51:"Commercie\Tests\Currency\CurrencyTest::testGetLabel";d:0.001;s:58:"Commercie\Tests\Currency\Currenc
This file must be removed. It was probably added before `.gitignore` was updated :)

2021-07-15 05:57 UTC, TomKeyte commented
Updated

2021-07-15 09:37 UTC, bartfeenstra approved these changes

2021-07-15 09:43 UTC, bartfeenstra commented
Thanks! It seems Travis has made some changes in recent months and I'm working on re-enabling builds so we can confirm everything works on PHP 8.

2021-07-16 11:26 UTC, bartfeenstra commented
I can't see why this repository is now showing up in my Travis CI dashboard, and without that happening I cannot reenable builds to ensure these changes work. As I have moved away from e-commerce some years ago and no longer maintain this or any other e-commerce package, as well as no longer use Travis CI for any of my active repositories, unfortunately I have limited time to spend on this.

2022-09-11 08:26 UTC, Berdir commented
Merging this, I did run the tests manually on PHP 8, created a follow-up to convert the travis stuff to github actions: #7

2022-09-11 08:27 UTC, merged

2022-09-11 11:17 UTC, Berdir commented
One note:

> Removing support for EOL versions would be a BC break and require a new major version release.

Note that semver allows to change versions and even add/remove dependencies in minor versions, and strictly speaking, the changes here require 7.1 at least (the void return type), so it would have been correct update that accordingly, but it only affects running tests. 

I did make that change in https://github.com/Commercie/currency-exchange/pull/3 though. might update this here if/when working on #7.